# -*- coding: utf-8 -*-
"""LARGE_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5dU6OzaJJF0FRC3OXKWOpoR8YNlWcof

# LARGE Models (8B – 16B Parameters)
# Models: aya-expanse-8b, Fanar-1-9B-Instruct, Moonlight-16B-A3B-Instruct
"""

# --- Cell 1: Quantized Heavy Inference Setup ---
!pip install -q transformers datasets torch accelerate jiwer tqdm pandas bitsandbytes

import re, gc, torch, jiwer, pandas as pd
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from tqdm import tqdm

SAMPLE_SIZE = 600
CACHE_DIR = "./model_cache"  # directory where downloaded models/tokenizers are cached
ARABIC_DIACRITICS = re.compile(r'[\u064B-\u0652]')
skipped_models = []

if not torch.cuda.is_available():
    print("WARNING: no CUDA device detected. 4-bit bitsandbytes quantization requires a GPU; "
          "all large models will be skipped rather than crash the run.")

# Configure 4-Bit NormalFloat Quantization for high memory efficiency
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16
)

"""# 2: Evaluation Suite"""

def strip_diacritics(text: str) -> str: return ARABIC_DIACRITICS.sub('', text)
def clean_and_tokenize(text: str) -> list: return re.sub(r'[^\w\s\u064B-\u0652]', '', text).split()
def strip_case_ending(word: str) -> str:
    idx = [i for i, ch in enumerate(word) if not ARABIC_DIACRITICS.match(ch)]
    return word[:idx[-1] + 1] if idx else word

def _align_words(predictions: list, references: list):
    for pred, ref in zip(predictions, references):
        p_words, r_words = clean_and_tokenize(pred), clean_and_tokenize(ref)
        p_skel, r_skel = [strip_diacritics(w) for w in p_words], [strip_diacritics(w) for w in r_words]
        alignment = jiwer.process_words(" ".join(r_skel), " ".join(p_skel))
        for chunk in alignment.alignments[0]:
            if chunk.type == "equal":
                for i in range(chunk.ref_start_idx, chunk.ref_end_idx):
                    yield r_words[i], p_words[chunk.hyp_start_idx + (i - chunk.ref_start_idx)]
            elif chunk.type in ("substitute", "delete"):
                for i in range(chunk.ref_start_idx, chunk.ref_end_idx):
                    yield r_words[i], None

def compute_der_wer(predictions: list, references: list) -> dict:
    total_chars, wrong_chars, total_words, wrong_words = 0, 0, 0, 0
    total_chars_noce, wrong_chars_noce, wrong_words_noce = 0, 0, 0

    for r_word, p_word in _align_words(predictions, references):
        total_words += 1
        r_word_noce, p_word_noce = strip_case_ending(r_word), strip_case_ending(p_word) if p_word else None

        if p_word is None:
            wrong_words += 1
            wrong_words_noce += 1
            n = max(len(ARABIC_DIACRITICS.findall(r_word)), 1)
            total_chars += n
            wrong_chars += n
            n_noce = max(len(ARABIC_DIACRITICS.findall(r_word_noce)), 1)
            total_chars_noce += n_noce
            wrong_chars_noce += n_noce
            continue

        if r_word != p_word: wrong_words += 1
        if r_word_noce != p_word_noce: wrong_words_noce += 1

        r_d, p_d = ARABIC_DIACRITICS.findall(r_word), ARABIC_DIACRITICS.findall(p_word)
        n = max(len(r_d), len(p_d), 1)
        total_chars += n
        if r_d != p_d:
            mism = sum(1 for a, b in zip(r_d, p_d) if a != b) + abs(len(r_d) - len(p_d))
            wrong_chars += max(mism, 1)

        r_d_n, p_d_n = ARABIC_DIACRITICS.findall(r_word_noce), ARABIC_DIACRITICS.findall(p_word_noce)
        n_n = max(len(r_d_n), len(p_d_n), 1)
        total_chars_noce += n_n
        if r_d_n != p_d_n:
            mism = sum(1 for a, b in zip(r_d_n, p_d_n) if a != b) + abs(len(r_d_n) - len(p_d_n))
            wrong_chars_noce += max(mism, 1)

    return {
        "DER_ce": round((wrong_chars / total_chars) * 100, 2) if total_chars else 0.0,
        "DER_noce": round((wrong_chars_noce / total_chars_noce) * 100, 2) if total_chars_noce else 0.0,
        "WER_ce": round((wrong_words / total_words) * 100, 2) if total_words else 0.0,
        "WER_noce": round((wrong_words_noce / total_words) * 100, 2) if total_words else 0.0,
    }

"""
# 3: Data Parsing
"""

try:
    dataset = load_dataset("Misraj/SadeedDiac-25", split="train")
except Exception as e:
    print(f"FATAL: could not load dataset: {e}")
    dataset = []

msa_samples = [{"ground_truth": x["output"], "raw_input": strip_diacritics(x["input"])}
               for x in dataset if "fadel" not in x.get("filename","").lower()][:SAMPLE_SIZE]
ca_samples = [{"ground_truth": x["output"], "raw_input": strip_diacritics(x["input"])}
              for x in dataset if "fadel" in x.get("filename","").lower()][:SAMPLE_SIZE]

"""# 4: Heavy Model Runner"""

def load_large_model(model_id, label):
    print(f"Loading Quantized Heavy Model: {label} [{model_id}]...")
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True, cache_dir=CACHE_DIR)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=quantization_config,
            device_map="auto",
            trust_remote_code=True,
            cache_dir=CACHE_DIR,
        )
        model.eval()
        return model, tokenizer
    except Exception as e:
        skipped_models.append((label, str(e)))
        print(f"Skipping {label}: {e}")
        return None, None

def infer_large_model(model, tokenizer, test_dataset, label):
    predictions, references = [], [x["ground_truth"] for x in test_dataset]

    for item in tqdm(test_dataset, desc=f"Evaluating {label}"):
        try:
            system_prompt = "قم بتشكيل النص العربي التالي تشكيلاً كاملاً ودقيقاً دون أي إضافة:"
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": item["raw_input"]}
            ]

            if hasattr(tokenizer, "apply_chat_template"):
                prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            else:
                prompt = f"{system_prompt}\n\nالنص: {item['raw_input']}\nالتشكيل:"

            # Use model.device rather than a hardcoded "cuda" -- with device_map="auto" the
            # model may be sharded, and model.device still resolves to the right input device.
            inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

            with torch.no_grad():
                # do_sample=False (greedy) makes temperature meaningless/contradictory, so it's omitted.
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=512,
                    do_sample=False
                )

            raw_pred = tokenizer.decode(outputs[0][inputs.input_ids.shape[-1]:], skip_special_tokens=True)
            # Extract the line corresponding to the prediction output
            clean_pred = raw_pred.strip().split("\n")[0]
            predictions.append(clean_pred)
        except Exception as e:
            print(f"  [warn] {label}: inference failed on a sample, using empty prediction ({e})")
            predictions.append("")

    return compute_der_wer(predictions, references)

"""#5: Execution & Results"""

large_models = {
    "Aya-Expanse-8B": "CohereLabs/aya-expanse-8b",
    "Fanar-1-9B-Instruct": "Fanar-1-9B-Instruct",
    "Moonlight-16B-A3B-Instruct": "moonshotai/Moonlight-16B-A3B-Instruct"
}

domains = [("MSA (Modern)", msa_samples), ("CA (Classical)", ca_samples)]
large_records = []

# Outer loop: models -> load once (these are 8B-16B, reloading per-domain would double
# download/VRAM cost). Inner loop: domains (MSA, then CA).
# GPU memory is freed after each model finishes both domains, before loading the next.
for label, path in large_models.items():
    print(f"\n{'='*60}\n Loading model: {label}  ({path})\n{'='*60}")
    model, tokenizer = None, None

    if not torch.cuda.is_available():
        skipped_models.append((label, "No CUDA device available for 4-bit quantized inference"))
        print(f"Skipping {label}: no CUDA device available.\n")
        continue

    try:
        model, tokenizer = load_large_model(path, label)
        if model is None:
            print(f"Skipping {label}: model failed to load.\n")
            continue

        for domain, test_set in domains:
            metrics = infer_large_model(model, tokenizer, test_set, label)
            if metrics:
                metrics.update({"Model": label, "Domain Track": domain})
                large_records.append(metrics)
    except Exception as e:
        skipped_models.append((label, f"Unexpected failure: {e}"))
        print(f"Skipping {label}: unexpected failure ({e}).\n")
    finally:
        # --- Free the GPU before loading the next (large!) model, no matter what happened ---
        del model, tokenizer
        torch.cuda.empty_cache()
        gc.collect()
        print(f"Finished {label} — GPU cache cleared.\n")

"""# 6: Results Report"""

performance_df = pd.DataFrame(large_records)

if performance_df.empty:
    full_df = performance_df
    print("No models produced results \u2014 check the skip log below.")
else:
    metric_cols = ["DER_ce", "DER_noce", "WER_ce", "WER_noce"]

    mean_df = (
        performance_df
        .groupby("Model")[metric_cols]
        .mean()
        .round(2)
        .reset_index()
    )
    mean_df.insert(1, "Domain Track", "Mean (MSA + CA)")

    full_df = pd.concat([performance_df, mean_df], ignore_index=True)
    full_df["Domain Track"] = pd.Categorical(
        full_df["Domain Track"],
        categories=["MSA (Modern)", "CA (Classical)", "Mean (MSA + CA)"],
        ordered=True,
    )
    full_df = full_df.sort_values(["Model", "Domain Track"]).reset_index(drop=True)

print("\n=== LARGE / MOE MODELS EVALUATION MATRIX ===")
print(full_df.to_markdown(index=False) if not full_df.empty else "No models processed.")

try:
    results_path = "large_models_results.csv"
    full_df.to_csv(results_path, index=False)
    print(f"\nResults saved to {results_path}")
except Exception as e:
    print(f"\n[warn] Could not save results CSV: {e}")

if skipped_models:
    print("\n================ SKIPPED / FAILED MODELS (explicit) ================")
    for name, reason in skipped_models:
        print(f"- {name}: {reason}")
else:
    print("\nAll registered models ran successfully \u2014 no gaps in the table above.")