# -*- coding: utf-8 -*-
"""Small_Models_Test_Results (v5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19agP7VO6ydB_WpDOBoPnazomgsYRL0vS

# SMALL Models (< 500M Parameters)
# Models: Fine-Tashkeel, Tashkeel-350M-v2
"""

!pip install -q transformers datasets torch accelerate jiwer tqdm ipywidgets pandas

import re
import sys
import gc
import torch
import pandas as pd
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM
from tqdm.auto import tqdm
import jiwer

SAMPLE_SIZE = 600  # 600 CA + 600 MSA = 1200 samples total
CACHE_DIR = "./model_cache"  # directory where downloaded models/tokenizers are cached
skipped_models = []
ARABIC_DIACRITICS = re.compile(r'[\u064B-\u0652]')

"""# 2: Normalization & Evaluation Engine"""

def strip_diacritics(text: str) -> str:
    return ARABIC_DIACRITICS.sub('', text)

def clean_and_tokenize(text: str) -> list:
    cleaned = re.sub(r'[^\w\s\u064B-\u0652]', '', text)
    return cleaned.split()

def strip_case_ending(word: str) -> str:
    last_base_idx = None
    for i, ch in enumerate(word):
        if not ARABIC_DIACRITICS.match(ch):
            last_base_idx = i
    if last_base_idx is None:
        return word
    return word[:last_base_idx + 1]

def _align_words(predictions: list, references: list):
    for pred, ref in zip(predictions, references):
        pred_words = clean_and_tokenize(pred)
        ref_words = clean_and_tokenize(ref)
        pred_skel = [strip_diacritics(w) for w in pred_words]
        ref_skel = [strip_diacritics(w) for w in ref_words]

        alignment = jiwer.process_words(" ".join(ref_skel), " ".join(pred_skel))

        for chunk in alignment.alignments[0]:
            if chunk.type == "equal":
                for i in range(chunk.ref_start_idx, chunk.ref_end_idx):
                    r_word = ref_words[i]
                    p_word = pred_words[chunk.hyp_start_idx + (i - chunk.ref_start_idx)]
                    yield r_word, p_word
            elif chunk.type in ("substitute", "delete"):
                for i in range(chunk.ref_start_idx, chunk.ref_end_idx):
                    yield ref_words[i], None

def compute_der(predictions: list, references: list, ce: bool = True) -> float:
    total_chars, wrong_chars = 0, 0
    for r_word, p_word in _align_words(predictions, references):
        if ce is False:
            r_word = strip_case_ending(r_word)
            if p_word is not None:
                p_word = strip_case_ending(p_word)
        r_diacs = ARABIC_DIACRITICS.findall(r_word)
        n = max(len(r_diacs), 1)
        if p_word is None:
            total_chars += n
            wrong_chars += n
            continue
        p_diacs = ARABIC_DIACRITICS.findall(p_word)
        n = max(len(r_diacs), len(p_diacs), 1)
        total_chars += n
        if r_diacs != p_diacs:
            mism = sum(1 for a, b in zip(r_diacs, p_diacs) if a != b)
            mism += abs(len(r_diacs) - len(p_diacs))
            wrong_chars += max(mism, 1)
    return round((wrong_chars / total_chars) * 100, 2) if total_chars > 0 else 0.0

def compute_wer(predictions: list, references: list, ce: bool = True) -> float:
    total_words, wrong_words = 0, 0
    for r_word, p_word in _align_words(predictions, references):
        total_words += 1
        if p_word is None:
            wrong_words += 1
            continue
        if ce is False:
            r_word = strip_case_ending(r_word)
            p_word = strip_case_ending(p_word)
        if r_word != p_word:
            wrong_words += 1
    return round((wrong_words / total_words) * 100, 2) if total_words > 0 else 0.0

def compute_der_wer(predictions: list, references: list) -> dict:
    return {
        "DER_ce": compute_der(predictions, references, ce=True),
        "DER_noce": compute_der(predictions, references, ce=False),
        "WER_ce": compute_wer(predictions, references, ce=True),
        "WER_noce": compute_wer(predictions, references, ce=False),
    }

"""# 3: Dataset Ingestion"""

print("Loading SadeedDiac-25 Dataset...")
try:
    dataset = load_dataset("Misraj/SadeedDiac-25", split="train")
except Exception as e:
    print(f"FATAL: could not load dataset: {e}")
    dataset = []

msa_samples, ca_samples = [], []

for item in dataset:
    try:
        text_input = item.get("input", "")
        text_output = item.get("output", "")
        source = item.get("filename", "").lower()
        sample = {"ground_truth": text_output, "raw_input": strip_diacritics(text_input)}
        if "fadel" in source or source in ["religion", "classical_poetry", "hadith"]:
            ca_samples.append(sample)
        else:
            msa_samples.append(sample)
    except Exception as e:
        print(f"Skipping malformed dataset row: {e}")
        continue

msa_test_set = msa_samples[:SAMPLE_SIZE]
ca_test_set = ca_samples[:SAMPLE_SIZE]

"""# 4: Inference Pipelines"""

device = "cuda" if torch.cuda.is_available() else "cpu"

# ---------- Fine-Tashkeel (seq2seq) ----------
def load_seq2seq(model_id, desc_tag):
    print(f"Loading Seq2Seq: {model_id}...")
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=CACHE_DIR)
        model = AutoModelForSeq2SeqLM.from_pretrained(model_id, cache_dir=CACHE_DIR).to(device)
        model.eval()
        return model, tokenizer
    except Exception as e:
        skipped_models.append((desc_tag, str(e)))
        return None, None

def infer_seq2seq(model, tokenizer, test_dataset, desc_tag):
    predictions, references = [], [x["ground_truth"] for x in test_dataset]
    for item in tqdm(test_dataset, desc=f"Inference {desc_tag}"):
        try:
            inputs = tokenizer(item["raw_input"], return_tensors="pt",
                                max_length=1024, truncation=True).to(model.device)
            with torch.no_grad():
                outputs = model.generate(**inputs, max_length=1024)
            predictions.append(tokenizer.decode(outputs[0], skip_special_tokens=True))
        except Exception as e:
            print(f"  [warn] {desc_tag}: inference failed on a sample, using empty prediction ({e})")
            predictions.append("")
    return compute_der_wer(predictions, references)


# ---------- Tashkeel-350M-v2 (causal, chat-template based) ----------
def load_causal_chat(model_id, desc_tag):
    print(f"Loading CausalLM (chat template): {model_id}...")
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=CACHE_DIR)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            torch_dtype="bfloat16",
            cache_dir=CACHE_DIR,
        )
        model.eval()
        return model, tokenizer
    except Exception as e:
        skipped_models.append((desc_tag, str(e)))
        return None, None

def infer_causal_chat(model, tokenizer, test_dataset, desc_tag):
    predictions, references = [], [x["ground_truth"] for x in test_dataset]
    for item in tqdm(test_dataset, desc=f"Inference {desc_tag}"):
        try:
            model_inputs = tokenizer.apply_chat_template(
                [{"role": "user", "content": "قم بتشكيل هذا النص" + ":\n" + item["raw_input"]}],
                add_generation_prompt=True,
                return_tensors="pt",
                tokenize=True,
                return_dict=True,
            ).to(model.device)
            with torch.no_grad():
                # NOTE: max_new_tokens must be set explicitly -- without it, generate()
                # falls back to a ~20-token default which truncates diacritized output.
                output = model.generate(**model_inputs, max_new_tokens=1024, do_sample=False)
            input_len = model_inputs["input_ids"].shape[-1]
            pred_text = tokenizer.decode(output[0, input_len:], skip_special_tokens=True)
            predictions.append(pred_text.strip())
        except Exception as e:
            print(f"  [warn] {desc_tag}: inference failed on a sample, using empty prediction ({e})")
            predictions.append("")
    return compute_der_wer(predictions, references)

"""# 5: Model Execution Registry"""

model_registry = {
    "Fine-Tashkeel": {"repo": "basharalrfooh/Fine-Tashkeel", "type": "seq2seq"},
    "Tashkeel-350M-v2": {"repo": "Etherll/Tashkeel-350M-v2", "type": "causal_chat"},
}

domains = [("MSA (Modern)", msa_test_set), ("CA (Classical)", ca_test_set)]
benchmark_records = []

# Outer loop: models  ->  load once
# Inner loop: domains (MSA, then CA) -> run 600 + 600 = 1200 samples per model
# After a model finishes both domains, free the GPU before loading the next one.
for label, meta in model_registry.items():
    print(f"\n{'='*60}\n Loading model: {label}  ({meta['repo']})\n{'='*60}")

    try:
        if meta["type"] == "seq2seq":
            model, tokenizer = load_seq2seq(meta["repo"], label)
            infer_fn = infer_seq2seq
        elif meta["type"] == "causal_chat":
            model, tokenizer = load_causal_chat(meta["repo"], label)
            infer_fn = infer_causal_chat
        else:
            model, tokenizer = None, None
            infer_fn = None

        if model is None:
            print(f"Skipping {label}: model failed to load.\n")
            continue

        for domain, test_set in domains:
            metrics = infer_fn(model, tokenizer, test_set, label)
            if metrics:
                metrics.update({"Model": label, "Domain Track": domain})
                benchmark_records.append(metrics)
    except Exception as e:
        skipped_models.append((label, f"Unexpected failure: {e}"))
        print(f"Skipping {label}: unexpected failure ({e}).\n")
    finally:
        # --- Free the GPU before loading the next model, no matter what happened ---
        try:
            del model, tokenizer
        except NameError:
            pass
        torch.cuda.empty_cache()
        gc.collect()
        print(f"Finished {label} — GPU cache cleared.\n")

"""# 6: Results Report"""

performance_df = pd.DataFrame(benchmark_records)

if performance_df.empty:
    full_df = performance_df
    print("No models produced results \u2014 check the skip log below.")
else:
    # --- Mean row per model: average of MSA and CA (i.e. across domains) ---
    metric_cols = ["DER_ce", "DER_noce", "WER_ce", "WER_noce"]

    mean_df = (
        performance_df
        .groupby("Model")[metric_cols]
        .mean()
        .round(2)
        .reset_index()
    )
    mean_df.insert(1, "Domain Track", "Mean (MSA + CA)")

    full_df = pd.concat([performance_df, mean_df], ignore_index=True)
    full_df["Domain Track"] = pd.Categorical(
        full_df["Domain Track"],
        categories=["MSA (Modern)", "CA (Classical)", "Mean (MSA + CA)"],
        ordered=True,
    )
    full_df = full_df.sort_values(["Model", "Domain Track"]).reset_index(drop=True)

print("\n=== SMALL MODELS EVALUATION MATRIX (WITH MSA / CA MEAN ROW) ===")
print(full_df.to_markdown(index=False) if not full_df.empty else "No models processed.")

try:
    results_path = "small_models_results.csv"
    full_df.to_csv(results_path, index=False)
    print(f"\nResults saved to {results_path}")
except Exception as e:
    print(f"\n[warn] Could not save results CSV: {e}")

if skipped_models:
    print("\n================ SKIPPED / FAILED MODELS (explicit) ================")
    for name, reason in skipped_models:
        print(f"- {name}: {reason}")
else:
    print("\nAll registered models ran successfully \u2014 no gaps in the table above.")